import type { EverydayItem } from "../../domain/itemTypes";

export const foodAndDrinkItems: EverydayItem[] = [
  {
    id: "single-banana",
    name: "Single banana",
    category: "food-drink",
    approxUsdCents: 35,
    description: "A simple grab-and-go piece of fruit from a grocery checkout.",
    featuredOnTimeline: true,
  },
  {
    id: "espresso-shot",
    name: "Espresso shot",
    category: "food-drink",
    approxUsdCents: 300,
    description: "A plain café espresso with no extras.",
    featuredOnTimeline: true,
  },
  {
    id: "pizza-slice",
    name: "City pizza slice",
    category: "food-drink",
    approxUsdCents: 425,
    description: "A single quick pizza slice on the go.",
    featuredOnTimeline: true,
  },
  {
    id: "bagel-and-cream-cheese",
    name: "Bagel with cream cheese",
    category: "food-drink",
    approxUsdCents: 450,
    description: "A common breakfast stop.",
    featuredOnTimeline: false,
  },
  {
    id: "starbucks-coffee",
    name: "Basic Starbucks coffee",
    category: "food-drink",
    approxUsdCents: 500,
    description: "A plain coffee from a major chain.",
    featuredOnTimeline: true,
  },
  {
    id: "cold-brew",
    name: "Cold brew coffee",
    category: "food-drink",
    approxUsdCents: 650,
    description: "A typical café cold brew.",
    featuredOnTimeline: false,
  },
  {
    id: "smoothie",
    name: "Fruit smoothie",
    category: "food-drink",
    approxUsdCents: 750,
    description: "A blended fruit drink from a smoothie shop.",
    featuredOnTimeline: false,
  },
  {
    id: "craft-beer-pint",
    name: "Craft beer pint",
    category: "food-drink",
    approxUsdCents: 850,
    description: "One pint at a local bar.",
    featuredOnTimeline: false,
  },
  {
    id: "chipotle-burrito",
    name: "Chipotle burrito",
    category: "food-drink",
    approxUsdCents: 1_000,
    description: "A regular burrito order with common toppings.",
    featuredOnTimeline: true,
  },
  {
    id: "burger-and-fries",
    name: "Burger and fries",
    category: "food-drink",
    approxUsdCents: 1_400,
    description: "A casual diner combo.",
    featuredOnTimeline: true,
  },
  {
    id: "movie-popcorn-soda",
    name: "Movie popcorn and soda",
    category: "food-drink",
    approxUsdCents: 1_600,
    description: "Classic theater snack combo.",
    featuredOnTimeline: false,
  },
  {
    id: "takeout-sushi",
    name: "Takeout sushi lunch",
    category: "food-drink",
    approxUsdCents: 1_800,
    description: "A basic lunch box from a neighborhood sushi counter.",
    featuredOnTimeline: false,
  },
  {
    id: "weekend-brunch",
    name: "Weekend brunch entrée",
    category: "food-drink",
    approxUsdCents: 2_200,
    description: "A typical brunch plate before tax and tip.",
    featuredOnTimeline: true,
  },
  {
    id: "date-night-dinner",
    name: "Date-night dinner entrée",
    category: "food-drink",
    approxUsdCents: 3_400,
    description: "A nicer entrée at a sit-down restaurant.",
    featuredOnTimeline: false,
  },
  {
    id: "steakhouse-dinner",
    name: "Steakhouse dinner",
    category: "food-drink",
    approxUsdCents: 5_500,
    description: "A pricier single-person dinner out.",
    featuredOnTimeline: true,
  },
];
