import type { EverydayItem } from "../../domain/itemTypes";

export const householdItems: EverydayItem[] = [
  {
    id: "carton-eggs",
    name: "Carton of eggs",
    category: "groceries-household",
    approxUsdCents: 425,
    description: "A dozen eggs with a little regional price swing.",
    featuredOnTimeline: false,
  },
  {
    id: "loaf-bread",
    name: "Loaf of sandwich bread",
    category: "groceries-household",
    approxUsdCents: 350,
    description: "A basic grocery-store loaf for lunches and toast.",
    featuredOnTimeline: false,
  },
  {
    id: "gallon-milk",
    name: "Gallon of milk",
    category: "groceries-household",
    approxUsdCents: 430,
    description: "A common household staple.",
    featuredOnTimeline: false,
  },
  {
    id: "jar-peanut-butter",
    name: "Jar of peanut butter",
    category: "groceries-household",
    approxUsdCents: 450,
    description: "A pantry standby for sandwiches and snacks.",
    featuredOnTimeline: false,
  },
  {
    id: "bag-rice",
    name: "Five-pound bag of rice",
    category: "groceries-household",
    approxUsdCents: 625,
    description: "A pantry basic that goes a long way.",
    featuredOnTimeline: false,
  },
  {
    id: "rotisserie-chicken",
    name: "Rotisserie chicken",
    category: "groceries-household",
    approxUsdCents: 899,
    description: "A classic grab-and-go grocery dinner helper.",
    featuredOnTimeline: true,
  },
  {
    id: "dish-soap",
    name: "Bottle of dish soap",
    category: "groceries-household",
    approxUsdCents: 399,
    description: "A routine kitchen supply purchase.",
    featuredOnTimeline: false,
  },
  {
    id: "shampoo",
    name: "Bottle of shampoo",
    category: "clothing-personal-care",
    approxUsdCents: 799,
    description: "A common personal-care restock.",
    featuredOnTimeline: false,
  },
  {
    id: "toothpaste",
    name: "Tube of toothpaste",
    category: "clothing-personal-care",
    approxUsdCents: 499,
    description: "A regular bathroom cabinet refill.",
    featuredOnTimeline: false,
  },
  {
    id: "toilet-paper",
    name: "Pack of toilet paper",
    category: "groceries-household",
    approxUsdCents: 1_299,
    description: "A standard household refill pack.",
    featuredOnTimeline: true,
  },
  {
    id: "laundry-detergent",
    name: "Laundry detergent",
    category: "groceries-household",
    approxUsdCents: 1_499,
    description: "A standard jug for a household laundry cycle.",
    featuredOnTimeline: true,
  },
  {
    id: "paper-towels",
    name: "Multi-pack of paper towels",
    category: "groceries-household",
    approxUsdCents: 1_699,
    description: "A warehouse-style household refill.",
    featuredOnTimeline: false,
  },
  {
    id: "winter-beanie",
    name: "Simple winter beanie",
    category: "clothing-personal-care",
    approxUsdCents: 1_800,
    description: "A basic knit hat for colder weather.",
    featuredOnTimeline: false,
  },
  {
    id: "basic-tshirt",
    name: "Basic t-shirt",
    category: "clothing-personal-care",
    approxUsdCents: 2_200,
    description: "A plain everyday t-shirt.",
    featuredOnTimeline: true,
  },
  {
    id: "running-shoes",
    name: "Running shoes",
    category: "clothing-personal-care",
    approxUsdCents: 9_500,
    description: "A mainstream pair of running shoes.",
    featuredOnTimeline: true,
  },
];
