import type { EverydayItem } from "../../domain/itemTypes";

export const largerPurchasesItems: EverydayItem[] = [
  {
    id: "movie-ticket",
    name: "Movie ticket",
    category: "travel-experiences",
    approxUsdCents: 1400,
    description: "A standard evening movie ticket in many US cities.",
    featuredOnTimeline: true,
  },
  {
    id: "monthly-gym-membership",
    name: "Monthly gym membership",
    category: "travel-experiences",
    approxUsdCents: 4500,
    description: "A mainstream gym plan without add-ons or premium perks.",
    featuredOnTimeline: true,
  },
  {
    id: "one-night-motel",
    name: "One night at a basic motel",
    category: "travel-experiences",
    approxUsdCents: 8500,
    description: "A straightforward roadside stay before taxes in many areas.",
    featuredOnTimeline: false,
  },
  {
    id: "economy-flight",
    name: "Budget one-way flight",
    category: "travel-experiences",
    approxUsdCents: 18000,
    description: "A domestic low-cost fare booked with a bit of flexibility.",
    featuredOnTimeline: true,
  },
  {
    id: "car-insurance-month",
    name: "Monthly car insurance",
    category: "transport",
    approxUsdCents: 19000,
    description: "A rough mid-range monthly premium for one vehicle.",
    featuredOnTimeline: false,
  },
  {
    id: "budget-smartphone",
    name: "Budget smartphone",
    category: "larger-purchases",
    approxUsdCents: 29900,
    description: "A decent entry-level unlocked smartphone.",
    featuredOnTimeline: true,
  },
  {
    id: "weekend-road-trip",
    name: "Weekend road trip budget",
    category: "travel-experiences",
    approxUsdCents: 35000,
    description: "Gas, snacks, and one modest hotel stay for a simple weekend.",
    featuredOnTimeline: false,
  },
  {
    id: "rent-studio-apartment",
    name: "One month of a modest studio apartment",
    category: "larger-purchases",
    approxUsdCents: 145000,
    description: "A rough rent estimate for a simple studio in many US markets.",
    featuredOnTimeline: true,
  },
  {
    id: "used-laptop",
    name: "Used laptop",
    category: "larger-purchases",
    approxUsdCents: 45000,
    description: "A reliable used machine for everyday work and browsing.",
    featuredOnTimeline: true,
  },
  {
    id: "new-laptop",
    name: "New mid-range laptop",
    category: "larger-purchases",
    approxUsdCents: 99900,
    description: "A solid new laptop for general productivity.",
    featuredOnTimeline: true,
  },
  {
    id: "used-car",
    name: "Older used car",
    category: "larger-purchases",
    approxUsdCents: 650000,
    description: "A rough price for an older but usable commuter car.",
    featuredOnTimeline: true,
  },
  {
    id: "semester-community-college",
    name: "Community college semester tuition",
    category: "larger-purchases",
    approxUsdCents: 180000,
    description: "A broad approximation for in-district community college tuition.",
    featuredOnTimeline: false,
  },
  {
    id: "used-motorcycle",
    name: "Used motorcycle",
    category: "larger-purchases",
    approxUsdCents: 420000,
    description: "A simple used commuter motorcycle in decent condition.",
    featuredOnTimeline: false,
  },
  {
    id: "weekend-festival-pass",
    name: "Weekend music festival pass",
    category: "travel-experiences",
    approxUsdCents: 42_000,
    description: "A multi-day event pass before food and travel.",
    featuredOnTimeline: false,
  },
  {
    id: "month-childcare",
    name: "One month of childcare",
    category: "larger-purchases",
    approxUsdCents: 95_000,
    description: "A rough monthly childcare bill in many metro areas.",
    featuredOnTimeline: true,
  },
  {
    id: "used-road-bike",
    name: "Used road bike",
    category: "larger-purchases",
    approxUsdCents: 125_000,
    description: "A decent used bike for commuting or weekend rides.",
    featuredOnTimeline: false,
  },
  {
    id: "starter-home-down-payment",
    name: "Starter-home down payment",
    category: "larger-purchases",
    approxUsdCents: 4500000,
    description: "A rough 10 percent down payment on a modest starter home.",
    featuredOnTimeline: true,
  },
  {
    id: "new-e-bike",
    name: "New commuter e-bike",
    category: "larger-purchases",
    approxUsdCents: 165_000,
    description: "A practical commuter e-bike from a mainstream brand.",
    featuredOnTimeline: false,
  },
];
