import type { EverydayItem } from "../../domain/itemTypes";

export const transportAndServicesItems: EverydayItem[] = [
  {
    id: "bus-fare",
    name: "Local bus fare",
    category: "transport",
    approxUsdCents: 250,
    description: "A single city bus ride.",
    featuredOnTimeline: true,
  },
  {
    id: "subway-fare",
    name: "Subway ride",
    category: "transport",
    approxUsdCents: 290,
    description: "A one-way metro ride.",
    featuredOnTimeline: false,
  },
  {
    id: "parking-meter-hour",
    name: "Parking meter hour",
    category: "transport",
    approxUsdCents: 350,
    description: "An hour of downtown metered parking.",
    featuredOnTimeline: false,
  },
  {
    id: "music-streaming",
    name: "Music streaming month",
    category: "subscriptions-digital",
    approxUsdCents: 1_099,
    description: "A mainstream monthly music subscription.",
    featuredOnTimeline: false,
  },
  {
    id: "video-streaming",
    name: "Video streaming month",
    category: "subscriptions-digital",
    approxUsdCents: 1_599,
    description: "One common video streaming subscription.",
    featuredOnTimeline: true,
  },
  {
    id: "car-wash-basic",
    name: "Basic car wash",
    category: "services-errands",
    approxUsdCents: 1200,
    description: "A simple drive-through wash.",
    featuredOnTimeline: true,
  },
  {
    id: "rideshare-short",
    name: "Short rideshare trip",
    category: "transport",
    approxUsdCents: 1800,
    description: "A quick ride across town.",
    featuredOnTimeline: false,
  },
  {
    id: "rideshare-airport",
    name: "Airport rideshare",
    category: "transport",
    approxUsdCents: 4500,
    description: "A ride to or from the airport.",
    featuredOnTimeline: true,
  },
  {
    id: "monthly-transit-pass",
    name: "Monthly transit pass",
    category: "transport",
    approxUsdCents: 9000,
    description: "A public transit pass for regular commuting.",
    featuredOnTimeline: true,
  },
  {
    id: "oil-change",
    name: "Oil change",
    category: "services-errands",
    approxUsdCents: 7000,
    description: "A basic synthetic oil service.",
    featuredOnTimeline: false,
  },
  {
    id: "haircut-basic",
    name: "Basic haircut",
    category: "services-errands",
    approxUsdCents: 3000,
    description: "A no-frills neighborhood haircut.",
    featuredOnTimeline: true,
  },
  {
    id: "dry-clean-shirt",
    name: "Dry-cleaned shirt",
    category: "services-errands",
    approxUsdCents: 450,
    description: "Professional cleaning for one shirt.",
    featuredOnTimeline: false,
  },
  {
    id: "shoe-repair",
    name: "Shoe repair",
    category: "services-errands",
    approxUsdCents: 2500,
    description: "A simple sole or heel repair.",
    featuredOnTimeline: false,
  },
  {
    id: "dog-grooming",
    name: "Dog grooming visit",
    category: "services-errands",
    approxUsdCents: 8500,
    description: "A full grooming appointment for a medium dog.",
    featuredOnTimeline: false,
  },
  {
    id: "laundromat-load",
    name: "Laundromat wash and dry",
    category: "services-errands",
    approxUsdCents: 900,
    description: "One full laundry load washed and dried.",
    featuredOnTimeline: false,
  },
  {
    id: "key-copy",
    name: "Key copy",
    category: "services-errands",
    approxUsdCents: 500,
    description: "A basic house key duplicate.",
    featuredOnTimeline: false,
  },
  {
    id: "bike-tune-up",
    name: "Bike tune-up",
    category: "services-errands",
    approxUsdCents: 9500,
    description: "A standard bicycle tune-up.",
    featuredOnTimeline: true,
  },
  {
    id: "car-registration",
    name: "Annual car registration",
    category: "transport",
    approxUsdCents: 15000,
    description: "A rough annual registration fee.",
    featuredOnTimeline: false,
  },
  {
    id: "phone-plan",
    name: "Cell phone plan month",
    category: "subscriptions-digital",
    approxUsdCents: 6_500,
    description: "A mainstream monthly phone bill for one line.",
    featuredOnTimeline: true,
  },
  {
    id: "home-internet",
    name: "Home internet month",
    category: "subscriptions-digital",
    approxUsdCents: 8_000,
    description: "A typical home internet plan.",
    featuredOnTimeline: true,
  },
];
